package org.owasp.cheatcode.report;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.stream.Collectors;

import org.owasp.cheatcode.harness.CellResult;

/**
 * The README table, generated from the recorded cells.
 *
 * <p>Generated rather than hand-written because a hand-written table drifts: the previous README
 * carried a count of passing and failing tests that had to be re-typed after every change, and a
 * footnote explaining a distinction the ✅/❌ vocabulary could not carry.
 */
final class MarkdownReport {

    private final List<CellResult> cells;

    MarkdownReport(List<CellResult> cells) {
        this.cells = cells;
    }

    String render() {
        StringBuilder out = new StringBuilder();
        out.append("<!-- Generated by ReportGenerator from target/cheatcode-results. Do not edit by hand. -->\n\n");

        Map<String, List<CellResult>> byPlatform = new TreeMap<>(
                cells.stream().collect(Collectors.groupingBy(c -> c.platform)));

        for (Map.Entry<String, List<CellResult>> platform : byPlatform.entrySet()) {
            renderPlatform(out, platform.getKey(), platform.getValue());
        }

        renderLegend(out);
        return out.toString();
    }

    private void renderPlatform(StringBuilder out, String platform, List<CellResult> platformCells) {
        CellResult sample = platformCells.get(0);
        out.append("### ").append(platform)
           .append(" — ").append(sample.osName)
           .append(", Java ").append(sample.javaVersion)
           .append("\n\n");

        List<String> columns = payloadColumns(platformCells);

        out.append("| Implementation |");
        for (String column : columns) {
            out.append(" `").append(column).append("` |");
        }
        out.append("\n| --- |");
        out.append(" :-: |".repeat(columns.size()));
        out.append('\n');

        Map<String, List<CellResult>> byImplementation = platformCells.stream()
                .collect(Collectors.groupingBy(c -> c.implementation, LinkedHashMap::new,
                         Collectors.toList()));

        List<Map.Entry<String, List<CellResult>>> ordered = new ArrayList<>(byImplementation.entrySet());
        ordered.sort(ReportGenerator.implementationOrder());

        boolean vulnerableHeaderWritten = false;
        boolean secureHeaderWritten = false;
        for (Map.Entry<String, List<CellResult>> entry : ordered) {
            boolean vulnerable = entry.getValue().get(0).vulnerableByDesign;
            if (vulnerable && !vulnerableHeaderWritten) {
                out.append("| **Vulnerable by design** |").append(" |".repeat(columns.size())).append('\n');
                vulnerableHeaderWritten = true;
            } else if (!vulnerable && !secureHeaderWritten) {
                out.append("| **Secure** |").append(" |".repeat(columns.size())).append('\n');
                secureHeaderWritten = true;
            }
            renderRow(out, entry.getKey(), entry.getValue(), columns);
        }
        out.append('\n');
    }

    private void renderRow(StringBuilder out, String implementation, List<CellResult> rowCells,
                           List<String> columns) {
        Map<String, CellResult> byLabel = new LinkedHashMap<>();
        for (CellResult cell : rowCells) {
            byLabel.put(cell.payloadShortLabel, cell);
        }

        out.append("| `").append(ReportGenerator.shortName(implementation)).append("` |");
        for (String column : columns) {
            CellResult cell = byLabel.get(column);
            if (cell == null) {
                out.append(" — |");
                continue;
            }
            out.append(' ')
               .append(ReportGenerator.verdictDot(cell.verdict))
               .append(' ')
               .append(ReportGenerator.shortCode(cell.actualOutcome));
            if (!CellResult.MATCH.equals(cell.status)) {
                out.append(" **!").append(cell.status).append("**");
            }
            out.append(" |");
        }
        out.append('\n');
    }

    private List<String> payloadColumns(List<CellResult> platformCells) {
        Set<String> columns = new LinkedHashSet<>();
        platformCells.stream()
                     .sorted(ReportGenerator.payloadOrder())
                     .forEach(c -> columns.add(c.payloadShortLabel));
        return new ArrayList<>(columns);
    }

    private void renderLegend(StringBuilder out) {
        out.append("**Verdict** — what the outcome means, given what the payload was trying to do:\n\n");
        for (String verdict : new String[] {"SAFE", "FUNCTIONALITY_LOST", "NEAR_MISS", "BREACH"}) {
            out.append("- ").append(ReportGenerator.verdictDot(verdict))
               .append(" **").append(verdict).append("** — ")
               .append(ReportGenerator.verdictMeaning(verdict)).append('\n');
        }

        out.append("\n**Outcome** — what actually happened:\n\n");
        out.append("| Code | Outcome | Meaning |\n| --- | --- | --- |\n");
        String[] outcomes = {
            "READ_OK", "SANITIZED_HIT", "REJECTED", "SANITIZED_MISS",
            "UNDETECTED_MISS", "REJECTED_BY_RUNTIME", "SECRET_DISCLOSED"
        };
        for (String outcome : outcomes) {
            out.append("| `").append(ReportGenerator.shortCode(outcome)).append("` | `")
               .append(outcome).append("` | ")
               .append(ReportGenerator.outcomeMeaning(outcome)).append(" |\n");
        }
    }
}
